# Generated by Django 5.1.1 on 2025-01-23 14:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import internSphereApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Company', 'Company'), ('Department', 'Department'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin'), ('InternshipCareerOffice', 'Internship & Career Office')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=15)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'Company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('Accounting', 'Accounting'), ('Computer Science', 'Computer Science'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('THM', 'THM')], max_length=50)),
                ('department_head', models.CharField(max_length=100)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'Department'}, on_delete=django.db.models.deletion.CASCADE, related_name='department_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.IntegerField(default=0)),
                ('internship_office_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('internship_office_approval_date', models.DateTimeField(blank=True, null=True)),
                ('department_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('department_approval_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='internSphereApp.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internSphereApp.evaluationquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('Accounting', 'Accounting'), ('Computer Science', 'Computer Science'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('THM', 'THM')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField(default=internSphereApp.models.default_deadline, null=True)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Open', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internSphereApp.company')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.internship'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internSphereApp.company')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internSphereApp.internship')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipCareerOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICU_director', models.CharField(max_length=100)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'InternshipCareerOffice'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stud_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('temporary_password', models.CharField(max_length=100)),
                ('profile_completed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('year_of_study', models.CharField(max_length=2)),
                ('skills', models.CharField(max_length=1000)),
                ('department', models.CharField(choices=[('Accounting', 'Accounting'), ('Computer Science', 'Computer Science'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('THM', 'THM')], max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('list_of_students', models.FileField(blank=True, null=True, upload_to='list_of_students/')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='stud_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='final_reports/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('company_approval_date', models.DateTimeField(blank=True, null=True)),
                ('internship_office_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('internship_office_approval_date', models.DateTimeField(blank=True, null=True)),
                ('department_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('department_approval_date', models.DateTimeField(blank=True, null=True)),
                ('supervisor_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('supervisor_approval_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='internSphereApp.stud_profile')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.stud_profile'),
        ),
        migrations.CreateModel(
            name='BiWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.PositiveIntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_hours_completed', models.PositiveIntegerField()),
                ('assignment_responsibilities', models.TextField()),
                ('critical_analysis', models.TextField()),
                ('observing_hours', models.PositiveIntegerField()),
                ('administrative_hours', models.PositiveIntegerField()),
                ('researching_hours', models.PositiveIntegerField()),
                ('assisting_hours', models.PositiveIntegerField()),
                ('misc_hours', models.PositiveIntegerField()),
                ('meetings_discussions', models.TextField()),
                ('course_relevance_suggestions', models.TextField()),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('company_approval_date', models.DateTimeField(blank=True, null=True)),
                ('internship_office_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('internship_office_approval_date', models.DateTimeField(blank=True, null=True)),
                ('department_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('department_approval_date', models.DateTimeField(blank=True, null=True)),
                ('supervisor_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('supervisor_approval_date', models.DateTimeField(blank=True, null=True)),
                ('application_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internSphereApp.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_reports', to='internSphereApp.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_reports', to='internSphereApp.stud_profile')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internSphereApp.stud_profile'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='internSphereApp.department')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'Supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='internSphereApp.stud_profile')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
