# Generated by Django 5.1.1 on 2025-01-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
