# Generated by Django 5.1.1 on 2024-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternshipOffice',
            new_name='Internship_Office',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Company', 'Company'), ('Department', 'Department'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin'), ('internship_office', 'internship_office')], max_length=50),
        ),
    ]
