# Generated by Django 5.1.1 on 2024-10-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='year_of_study',
            field=models.CharField(max_length=2),
        ),
    ]
