# Generated by Django 5.1.1 on 2024-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0002_alter_student_profile_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
    ]
