# Generated by Django 5.1.1 on 2024-10-07 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0003_alter_student_profile_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biweeklyreport',
            old_name='report_content',
            new_name='assignment_responsibilities',
        ),
        migrations.RenameField(
            model_name='biweeklyreport',
            old_name='report_period_end',
            new_name='week_end',
        ),
        migrations.RenameField(
            model_name='biweeklyreport',
            old_name='report_period_start',
            new_name='week_start',
        ),
        migrations.RemoveField(
            model_name='biweeklyreport',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='administrative_hours',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='assisting_hours',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='course_relevance_suggestions',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='critical_analysis',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='department_choices',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Computer Science', 'Computer Science'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('THM', 'THM')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='id_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='meetings_discussions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='misc_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='observing_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internSphereApp.student_profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='report_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='researching_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='section',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biweeklyreport',
            name='total_hours_completed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biweeklyreport',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
