# Generated by Django 5.1.1 on 2024-10-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0004_rename_report_content_biweeklyreport_assignment_responsibilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biweeklyreport',
            old_name='profile',
            new_name='student_profile',
        ),
        migrations.RenameField(
            model_name='biweeklyreport',
            old_name='student',
            new_name='user',
        ),
    ]
