# Generated by Django 5.1.1 on 2025-01-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0004_supervisorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignment', to='internSphereApp.stud_profile'),
        ),
        migrations.AlterField(
            model_name='supervisorassignment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_students', to='internSphereApp.supervisor'),
        ),
        migrations.CreateModel(
            name='SupervisorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biweekly_report_score', models.PositiveIntegerField(default=0)),
                ('final_report_score', models.PositiveIntegerField(default=0)),
                ('presentation_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_evaluations', to='internSphereApp.stud_profile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_evaluations', to='internSphereApp.supervisor')),
            ],
        ),
    ]
