# Generated by Django 5.1.1 on 2025-01-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0005_alter_supervisorassignment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorevaluation',
            name='biweekly_report_score',
        ),
        migrations.AddField(
            model_name='supervisorevaluation',
            name='bi_weekly_report_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_evaluations', to='internSphereApp.company'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_evaluations', to='internSphereApp.internship'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_evaluations', to='internSphereApp.stud_profile'),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='final_report_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='presentation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.stud_profile'),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.supervisor'),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='total_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
