# Generated by Django 5.1.1 on 2024-11-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0005_rename_student_profile_stud_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
