# Generated by Django 5.1.1 on 2024-10-15 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0006_alter_biweeklyreport_student_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biweeklyreport',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internSphereApp.student_profile'),
        ),
        migrations.AlterField(
            model_name='biweeklyreport',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
