# Generated by Django 5.1.1 on 2024-10-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0007_alter_biweeklyreport_student_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biweeklyreport',
            name='student_profile',
        ),
    ]
