# Generated by Django 5.1.1 on 2025-01-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0007_remove_supervisorevaluation_bi_weekly_report_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorevaluation',
            name='biweekly_report_score',
        ),
        migrations.RemoveField(
            model_name='supervisorevaluation',
            name='final_report_score',
        ),
        migrations.RemoveField(
            model_name='supervisorevaluation',
            name='presentation_score',
        ),
        migrations.AddField(
            model_name='supervisorevaluation',
            name='bi_weekly_report_marks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='supervisorevaluation',
            name='company_evaluation_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorevaluation',
            name='final_report_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorevaluation',
            name='presentation_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
