# Generated by Django 5.1.1 on 2024-12-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0007_remove_evaluation_company_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internSphereApp.company'),
        ),
    ]
