# Generated by Django 5.1.1 on 2025-01-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0008_remove_supervisorevaluation_biweekly_report_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorevaluation',
            name='bi_weekly_report_marks',
        ),
        migrations.RemoveField(
            model_name='supervisorevaluation',
            name='company_evaluation_score',
        ),
        migrations.AddField(
            model_name='supervisorevaluation',
            name='biweekly_marks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='final_report_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='presentation_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.stud_profile'),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.supervisor'),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
