# Generated by Django 5.1.1 on 2024-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0008_internship_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='sector',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Computer Science', 'Computer Science'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('THM', 'THM')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stud_profile',
            name='department',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Computer Science', 'Computer Science'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('THM', 'THM')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stud_profile',
            name='list_of_students',
            field=models.FileField(blank=True, null=True, upload_to='list_of_students/'),
        ),
    ]
