# Generated by Django 5.1.1 on 2025-01-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0009_remove_supervisorevaluation_bi_weekly_report_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='biweekly_marks',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_evaluations', to='internSphereApp.supervisor'),
        ),
    ]
