# Generated by Django 5.1.1 on 2024-11-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0010_rename_applied_at_application_applied_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biweeklyreport',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internSphereApp.company'),
            preserve_default=False,
        ),
    ]
