# Generated by Django 5.1.1 on 2025-01-29 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0010_alter_supervisorevaluation_biweekly_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_weekly_report_score', models.IntegerField(default=0)),
                ('final_report_score', models.IntegerField(default=0)),
                ('presentation_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.stud_profile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internSphereApp.supervisor')),
            ],
        ),
        migrations.DeleteModel(
            name='SupervisorEvaluation',
        ),
    ]
