# Generated by Django 5.1.1 on 2024-11-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0011_biweeklyreport_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='biweeklyreport',
            name='applicaion_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internSphereApp.application'),
            preserve_default=False,
        ),
    ]
