# Generated by Django 5.1.1 on 2025-01-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0011_studentevaluation_delete_supervisorevaluation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentEvaluation',
            new_name='SupervisorEvaluation',
        ),
    ]
