# Generated by Django 5.1.1 on 2024-11-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0012_biweeklyreport_applicaion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
