# Generated by Django 5.1.1 on 2024-11-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0013_application_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biweeklyreport',
            name='applicaion_status',
        ),
    ]
