# Generated by Django 5.1.1 on 2024-11-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0015_biweeklyreport_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internSphereApp.department'),
        ),
    ]
