# Generated by Django 5.1.1 on 2024-11-26 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internSphereApp', '0017_remove_finalreport_report_finalreport_report_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_profile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='stud_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
